package com.training.app
package utils

object Constants {
    val FIXED="FIXED"
    val RECURRING="RECURRING"
    val RETURN_REMINDER="RETURN_REMINDER"
    val MAINTENANCE_ALERT="MAINTENANCE_ALERT"
    val INVENTORY_ALERT="INVENTORY_ALERT"
    val ALLOCATION_ALERT="ALLOCATION_ALERT"
    val REMINDER="REMINDER"
    val ALLOCATION="ALLOCATION"
    val RETURN="RETURN"
    val MAINTENANCE="MAINTENANCE"
}
